import express from "express";
import controller from "../controllers/followUpController.js";
import authMiddleware from "../middleware/authMiddleware.js";
import requireOrganization from "../middleware/requireOrganization.js";
import requireModule from "../middleware/requireModule.js";
import requirePermission from "../middleware/requirePermission.js";
const router = express.Router();
router.use(authMiddleware, requireOrganization, requireModule("FOLLOW_UPS"), requireModule("LEADS"), requirePermission("LEADS_VIEW"), requirePermission("FOLLOW_UPS_VIEW"));
router.get("/", controller.list);
router.get("/:id", controller.show);
router.post("/", requirePermission("FOLLOW_UPS_CREATE"), controller.create);
router.patch("/:id/complete", requirePermission("FOLLOW_UPS_COMPLETE"), controller.complete);
router.patch("/:id", requirePermission("FOLLOW_UPS_EDIT"), controller.edit);
router.delete("/:id", requirePermission("FOLLOW_UPS_DELETE"), controller.delete);
export default router;
